/** Estilos de perfil, preferências, notificações e ajuda, calculados com a paleta ativa. */
import { StyleSheet } from 'react-native';

export function createContaStyles(colors) {
  const centralAjudaStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      alignItems: 'stretch',
      paddingHorizontal: 10,
    },
    card: {
      backgroundColor: colors.surfaceAlt,
      marginHorizontal: 18,
      marginTop: 20,
      marginBottom: 20,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 12,
      overflow: 'hidden',
    },
    cardTitle: {
      color: colors.textPrimary,
      fontSize: 20,
      fontWeight: 'bold',
      marginHorizontal: 18,
      marginTop: 18,
      marginBottom: 12,
    },
    itemMenu: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 18,
      paddingVertical: 18,
    },
    itemLeft: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
    },
    itemText: {
      color: colors.textPrimary,
      fontSize: 16,
      marginLeft: 15,
      flexShrink: 1,
    },
    divider: {
      height: 1,
      backgroundColor: colors.divider,
      marginHorizontal: 18,
    },
    cardInfo: {
      backgroundColor: colors.surface,
      marginHorizontal: 18,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 18,
      marginBottom: 20,
    },
    cardInfoTitle: {
      color: colors.textPrimary,
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 10,
    },
    cardInfoText: {
      color: colors.textSecondary,
      fontSize: 15,
      lineHeight: 22,
    },
    contactButton: {
      backgroundColor: colors.primary,
      marginHorizontal: 18,
      height: 56,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
    },
    contactText: {
      color: colors.onPrimary,
      fontSize: 17,
      fontWeight: 'bold',
      marginLeft: 10,
    },
  });

  const configuracoesStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      alignItems: 'stretch',
      paddingHorizontal: 10,
    },
    card: {
      backgroundColor: colors.surface,
      marginHorizontal: 18,
      marginTop: 18,
      borderRadius: 22,
      borderWidth: 2,
      borderColor: colors.border,
      paddingVertical: 5,
      overflow: 'hidden',
    },
    cardTitle: {
      color: colors.textPrimary,
      fontSize: 20,
      fontWeight: 'bold',
      marginHorizontal: 18,
      marginTop: 18,
      marginBottom: 12,
    },
    item: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 18,
      paddingVertical: 18,
    },
    itemLeft: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
    },
    itemText: {
      flexShrink: 1,
      color: colors.textPrimary,
      fontSize: 17,
      marginLeft: 15,
      fontWeight: '500',
    },
    divider: {
      height: 1,
      backgroundColor: colors.divider,
    },
  });

  const meuCadastroStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      alignItems: 'stretch',
      paddingHorizontal: 10,
    },
    card: {
      marginTop: 20,
      backgroundColor: colors.surface,
      marginHorizontal: 18,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 18,
    },
    profileRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
    },
    profileCircle: {
      width: 68,
      height: 68,
      borderRadius: 34,
      borderWidth: 2,
      borderColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
      backgroundColor: colors.surfaceAlt,
    },
    profileInfo: {
      flex: 1,
    },
    profileName: {
      color: colors.textPrimary,
      fontSize: 20,
      fontWeight: 'bold',
    },
    profileEmail: {
      color: colors.textSecondary,
      fontSize: 14,
      marginTop: 4,
    },
    profileSubtitle: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
    },
    cardTitle: {
      color: colors.textPrimary,
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 18,
    },
    input: {
      width: '100%',
      minHeight: 55,
      backgroundColor: colors.input,
      color: colors.textPrimary,
      fontSize: 16,
      borderRadius: 14,
      paddingHorizontal: 16,
      marginBottom: 15,
      borderWidth: 1,
      borderColor: colors.border,
    },
    itemButton: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 12,
      backgroundColor: colors.input,
      borderRadius: 14,
    },
    itemLeft: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
    },
    itemText: {
      flexShrink: 1,
      color: colors.textPrimary,
      fontSize: 16,
      marginLeft: 14,
    },
    saveButton: {
      backgroundColor: colors.primary,
      padding: 14,
      marginHorizontal: 18,
      marginTop: 10,
      height: 56,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
    },
    saveButtonText: {
      color: colors.onPrimary,
      fontSize: 15,
      fontWeight: 'bold',
    },
  });

  const notificacoesStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      alignItems: 'stretch',
      paddingHorizontal: 10,
    },
    subTitle: {
      color: colors.textSecondary,
      fontSize: 16,
      marginHorizontal: 20,
      marginTop: 20,
      marginBottom: 15,
    },
    card: {
      backgroundColor: colors.surface,
      marginHorizontal: 18,
      marginBottom: 15,
      borderRadius: 20,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardNova: {
      borderLeftWidth: 5,
      borderLeftColor: colors.primary,
    },
    iconContainer: {
      width: 55,
      height: 55,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 15,
    },
    textContainer: {
      flex: 1,
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    cardTitle: {
      color: colors.textPrimary,
      fontSize: 17,
      fontWeight: 'bold',
      flex: 1,
    },
    descricao: {
      color: colors.textSecondary,
      fontSize: 14,
      marginTop: 6,
      lineHeight: 20,
    },
    hora: {
      color: colors.textSecondary,
      fontSize: 13,
      marginLeft: 10,
    },
    bolinha: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.primary,
      marginLeft: 10,
      alignSelf: 'flex-start',
      marginTop: 8,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 30,
      marginTop: 80,
    },
    emptyTitle: {
      color: colors.textPrimary,
      fontSize: 22,
      fontWeight: 'bold',
      marginTop: 20,
    },
    emptyText: {
      color: colors.textSecondary,
      fontSize: 15,
      textAlign: 'center',
      marginTop: 10,
      lineHeight: 22,
    },
  });

  const perfilStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      alignItems: 'stretch',
      paddingHorizontal: 10,
    },
    profileContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      marginTop: 10,
      marginBottom: 30,
    },
    profileCircle: {
      width: 85,
      height: 85,
      borderRadius: 50,
      borderWidth: 4,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    profileInfo: {
      marginLeft: 18,
      flex: 1,
    },
    settingsButton: {
      marginLeft: 'auto',
      padding: 8,
      justifyContent: 'center',
      alignItems: 'center',
    },
    nome: {
      color: colors.textPrimary,
      fontSize: 24,
      fontWeight: 'bold',
    },
    email: {
      color: colors.textSecondary,
      fontSize: 15,
      marginTop: 4,
    },
    resumoCard: {
      backgroundColor: colors.surface,
      marginHorizontal: 15,
      borderRadius: 18,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 25,
    },
    resumoTitulo: {
      color: colors.textPrimary,
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 20,
    },
    resumoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    itemResumo: {
      alignItems: 'center',
      flex: 1,
    },
    labelResumo: {
      color: colors.textSecondary,
      fontSize: 12,
      marginTop: 8,
      marginBottom: 5,
      textAlign: 'center',
    },
    valorResumo: {
      color: colors.textPrimary,
      fontWeight: 'bold',
      fontSize: 13,
      textAlign: 'center',
    },
    menuCard: {
      backgroundColor: colors.surface,
      marginHorizontal: 15,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 20,
      overflow: 'hidden',
    },
    itemMenu: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 18,
      paddingVertical: 18,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    itemLeft: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
    },
    itemTexto: {
      flexShrink: 1,
      color: colors.textPrimary,
      fontSize: 16,
      marginLeft: 15,
    },
    modalBackground: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modal: {
      maxWidth: 520,
      width: '85%',
      backgroundColor: colors.surface,
      borderRadius: 25,
      padding: 25,
      alignItems: 'center',
    },
    modalIcon: {
      width: 75,
      height: 75,
      borderRadius: 40,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
    },
    modalTitulo: {
      color: colors.textPrimary,
      fontSize: 24,
      fontWeight: 'bold',
    },
    modalTexto: {
      color: colors.textSecondary,
      fontSize: 16,
      textAlign: 'center',
      marginTop: 12,
      marginBottom: 30,
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
    },
    cancelar: {
      width: '47%',
      minHeight: 50,
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    cancelarTexto: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: 'bold',
    },
    sair: {
      width: '47%',
      minHeight: 50,
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderRadius: 15,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sairTexto: {
      color: colors.onPrimary,
      fontSize: 16,
      fontWeight: 'bold',
    },
  });

  const sobreAppStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      alignItems: 'stretch',
      paddingHorizontal: 10,
    },
    mainCard: {
      backgroundColor: colors.surface,
      marginHorizontal: 18,
      marginTop: 10,
      borderRadius: 16,
      paddingVertical: 24,
      paddingHorizontal: 20,
      alignItems: 'center',
      marginBottom: 18,
      borderWidth: 1,
      borderColor: colors.border,
    },
    appName: {
      color: colors.textPrimary,
      fontSize: 28,
      fontWeight: '600',
    },
    featuresCard: {
      backgroundColor: colors.featuresCard,
      marginHorizontal: 18,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 16,
      marginBottom: 18,
    },
    featuresTitle: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 12,
    },
    featureRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: 14,
    },
    featureIcon: {
      width: 48,
      height: 48,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    featureTexts: {
      flex: 1,
    },
    featureTitle: {
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '700',
    },
    featureText: {
      color: colors.textSecondary,
      fontSize: 13,
      marginTop: 4,
    },
    infoCard: {
      backgroundColor: colors.surface,
      marginHorizontal: 18,
      borderRadius: 14,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    infoTitle: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: '700',
      marginBottom: 6,
    },
    infoText: {
      color: colors.textSecondary,
      fontSize: 13,
    },
    contactCard: {
      backgroundColor: colors.surface,
      marginHorizontal: 18,
      borderRadius: 14,
      padding: 14,
      marginBottom: 18,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    contactLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    contactText: {
      flexShrink: 1,
      color: colors.textPrimary,
      fontSize: 15,
      marginLeft: 10,
    },
    footer: {
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 30,
    },
    footerApp: {
      color: colors.textSecondary,
      fontSize: 14,
      marginBottom: 6,
    },
    footerCopy: {
      color: colors.textSecondary,
      fontSize: 12,
    },
  });
  return {
    centralAjudaStyles,
    configuracoesStyles,
    meuCadastroStyles,
    notificacoesStyles,
    perfilStyles,
    sobreAppStyles,
  };
}
