/** Estilos de resumo, lançamentos, metas e relatórios, calculados com a paleta ativa. */
import { StyleSheet } from 'react-native';

export function createFinanceiroStyles(colors, { radii, shadow }) {
  const dashboardStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      alignItems: 'stretch',
      paddingHorizontal: 10,
    },
  });

  const fluxoFinanceiroStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      alignItems: 'stretch',
      paddingHorizontal: 10,
    },
    filtroContainer: {
      flexDirection: 'row',
      backgroundColor: colors.surface,
      borderRadius: 30,
      padding: 3,
      marginTop: 10,
      marginHorizontal: 20,
      borderWidth: 1,
      borderColor: colors.border,
    },
    botaoFiltro: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 25,
      alignItems: 'center',
    },
    botaoAtivo: {
      backgroundColor: colors.primary,
    },
    textoFiltro: {
      color: colors.textPrimary,
      fontSize: 14,
    },
    textoAtivo: {
      color: colors.onPrimary,
      fontWeight: 'bold',
    },
    dados: {
      marginTop: 20,
      backgroundColor: colors.surface,
      borderRadius: 18,
      padding: 16,
      marginHorizontal: 20,
      marginBottom: 20,
    },
    dadosTitulo: {
      color: colors.textPrimary,
      fontSize: 18,
      fontWeight: '700',
      marginBottom: 16,
    },
    dadosTexto: {
      color: colors.textSecondary,
      fontSize: 14,
      marginTop: 12,
    },
    transacaoItem: {
      flexWrap: 'wrap',
      gap: 12,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    transacaoDescricao: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: '600',
    },
    transacaoCategoria: {
      color: colors.textSecondary,
      fontSize: 12,
      marginTop: 4,
    },
    transacaoDireita: {
      flexGrow: 1,
      flexShrink: 1,
      alignItems: 'flex-end',
    },
    transacaoValor: {
      fontSize: 16,
      fontWeight: '700',
    },
    receita: {
      color: colors.success,
    },
    despesa: {
      color: colors.danger,
    },
    transacaoData: {
      color: colors.textSecondary,
      fontSize: 12,
      marginTop: 4,
    },
  });

  const inicioStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      paddingTop: 18,
      paddingBottom: 26,
      paddingHorizontal: 16,
      borderBottomLeftRadius: radii.xl,
      borderBottomRightRadius: radii.xl,
    },
    profileContaine: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
      marginRight: 12,
      minWidth: 0,
    },
    profileCircle: {
      width: 70,
      height: 70,
      borderRadius: 35,
      borderWidth: 2.5,
      borderColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.surfaceAlt,
    },
    profileInfo: {
      marginLeft: 16,
      flexShrink: 1,
      minWidth: 0,
    },
    greetingLabel: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '500',
    },
    nome: {
      color: colors.textPrimary,
      fontSize: 21,
      fontWeight: 'bold',
      marginTop: 1,
    },
    bellButton: {
      width: 44,
      height: 44,
      flexShrink: 0,
      borderRadius: 22,
      backgroundColor: colors.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    saldoContainer: {
      marginTop: 20,
      padding: 20,
      borderRadius: radii.xl,
      minHeight: 140,
      ...shadow.glowPrimary,
    },
    saldoTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    titleSaldo: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.onPrimary,
    },
    valor: {
      marginTop: 10,
      fontSize: 36,
      fontWeight: 'bold',
      color: colors.onPrimary,
    },
    saldoFooterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 14,
    },
    saldoFooterText: {
      flexShrink: 1,
      color: colors.onPrimary,
      fontSize: 12,
      marginLeft: 6,
    },
    content: {
      paddingHorizontal: 16,
    },
    title: {
      fontSize: 18,
      marginTop: 22,
      marginBottom: 12,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    card: {
      backgroundColor: colors.surface,
      padding: 16,
      borderRadius: radii.lg,
      marginRight: 12,
      width: 160,
      minHeight: 150,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'flex-start',
    },
    cardIconBadge: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    cardTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    cardValue: {
      marginTop: 4,
      fontSize: 18,
      fontWeight: 'bold',
      color: colors.textPrimary,
    },
    cardDelta: {
      fontSize: 11,
      marginTop: 4,
      fontWeight: '600',
    },
    sectionCard: {
      backgroundColor: colors.surface,
      padding: 18,
      borderRadius: radii.lg,
      marginTop: 18,
      marginBottom: 25,
      borderWidth: 1,
      borderColor: colors.border,
    },
    metaHeaderRow: {
      flexWrap: 'wrap',
      gap: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 6,
    },
    metaHeaderTitle: {
      color: colors.textPrimary,
      fontSize: 17,
      fontWeight: '700',
    },
    verMetasBadge: {
      color: colors.onPrimary,
      backgroundColor: colors.primaryDeep,
      borderRadius: radii.pill,
      paddingHorizontal: 12,
      paddingVertical: 6,
      fontSize: 12,
      fontWeight: '600',
      overflow: 'hidden',
    },
    graficos: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 18,
    },
    metaInfoCol: {
      flexDirection: 'column',
      marginLeft: 18,
      flex: 1,
    },
    metaTituloTexto: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 10,
    },
    metaBarraFundo: {
      width: '100%',
      height: 7,
      backgroundColor: colors.surfaceElevated,
      borderRadius: 10,
      overflow: 'hidden',
    },
    metaBarraPreenchida: {
      height: 7,
      backgroundColor: colors.primary,
      borderRadius: 10,
    },
    metaValoresTexto: {
      color: colors.textMuted,
      fontSize: 13,
      marginTop: 8,
    },
  });

  const metasStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      alignItems: 'stretch',
      paddingHorizontal: 10,
    },
    card: {
      backgroundColor: colors.surfaceMuted,
      borderRadius: 20,
      padding: 18,
      marginHorizontal: '5%',
      marginBottom: 18,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 15,
    },
    cardConcluida: {
      borderWidth: 1,
      borderColor: colors.success,
    },
    acoesCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    botaoAcao: {
      width: 38,
      height: 38,
      borderRadius: 12,
      backgroundColor: colors.surfaceElevated,
      justifyContent: 'center',
      alignItems: 'center',
    },
    nomeMeta: {
      color: colors.textPrimary,
      fontSize: 20,
      fontWeight: 'bold',
      marginLeft: 12,
      flex: 1,
    },
    progressBackground: {
      width: '100%',
      height: 10,
      backgroundColor: colors.surfaceElevated,
      borderRadius: 50,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      backgroundColor: colors.primary,
      borderRadius: 50,
    },
    progressFillConcluida: {
      backgroundColor: colors.success,
    },
    concluidaBadge: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 7,
      paddingHorizontal: 10,
      borderRadius: 12,
      backgroundColor: colors.surfaceElevated,
      marginBottom: 12,
    },
    concluidaTexto: {
      color: colors.success,
      fontSize: 14,
      fontWeight: 'bold',
    },
    infoLinha: {
      flexWrap: 'wrap',
      gap: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 12,
    },
    valor: {
      color: colors.textSecondary,
      fontSize: 15,
    },
    statusMeta: {
      color: colors.textSecondary,
      fontSize: 14,
      marginTop: 8,
    },
    statusConcluida: {
      color: colors.success,
      fontWeight: 'bold',
    },
    porcentagem: {
      color: colors.textLink,
      fontWeight: 'bold',
      fontSize: 20,
      marginTop: 12,
      textAlign: 'right',
    },
    porcentagemConcluida: {
      color: colors.success,
    },
    botaoAdicionar: {
      position: 'absolute',
      bottom: 95,
      alignSelf: 'center',
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primary,
      paddingHorizontal: 25,
      height: 55,
      borderRadius: 30,
      elevation: 10,
    },
    botaoTexto: {
      color: colors.onPrimary,
      fontSize: 17,
      fontWeight: 'bold',
      marginLeft: 8,
    },
    modalBackground: {
      flexGrow: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 25,
    },
    modal: {
      maxWidth: 520,
      width: '100%',
      backgroundColor: colors.surfaceMuted,
      borderRadius: 25,
      padding: 22,
    },
    modalBackgroundExcluir: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 25,
    },
    modalExcluir: {
      maxWidth: 460,
      width: '100%',
      backgroundColor: colors.surfaceMuted,
      borderRadius: 25,
      padding: 22,
      alignItems: 'center',
    },
    iconeExcluir: {
      width: 58,
      height: 58,
      borderRadius: 29,
      backgroundColor: colors.surfaceElevated,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    textoConfirmacao: {
      color: colors.textSecondary,
      fontSize: 15,
      lineHeight: 22,
      textAlign: 'center',
      marginBottom: 8,
    },
    modalTitulo: {
      color: colors.textPrimary,
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 20,
      textAlign: 'center',
    },
    input: {
      width: '100%',
      minHeight: 55,
      backgroundColor: colors.input,
      borderRadius: 14,
      paddingHorizontal: 15,
      color: colors.textPrimary,
      fontSize: 16,
      marginBottom: 15,
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 10,
    },
    cancelar: {
      width: '47%',
      minHeight: 50,
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderWidth: 1,
      borderColor: colors.primary,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
    },
    cancelarTexto: {
      color: colors.textPrimary,
      fontWeight: 'bold',
      fontSize: 16,
    },
    salvar: {
      width: '47%',
      minHeight: 50,
      paddingVertical: 12,
      paddingHorizontal: 8,
      backgroundColor: colors.primary,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
    },
    salvarTexto: {
      color: colors.onPrimary,
      fontWeight: 'bold',
      fontSize: 16,
    },
    excluir: {
      width: '47%',
      minHeight: 50,
      paddingVertical: 12,
      paddingHorizontal: 8,
      backgroundColor: colors.danger,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
    },
    excluirTexto: {
      color: colors.onPrimary,
      fontWeight: 'bold',
      fontSize: 16,
    },
  });

  const novaDespesaStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      alignItems: 'stretch',
      paddingHorizontal: 10,
    },
    titulo: {
      flexShrink: 1,
      color: colors.textPrimary,
      marginLeft: 10,
      fontSize: 19,
      fontWeight: '600',
    },
    addValor: {
      flexWrap: 'wrap',
      gap: 12,
      flexDirection: 'row',
      backgroundColor: colors.surfaceMuted,
      padding: 12,
      margin: 16,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    InputValor: {
      color: colors.danger,
      borderRadius: 10,
      flexGrow: 1,
      flexBasis: 140,
      minWidth: 0,
      backgroundColor: colors.input,
      minHeight: 46,
      paddingHorizontal: 10,
      justifyContent: 'center',
      fontWeight: '600',
      fontSize: 17,
    },
    input: {
      width: '100%',
      minHeight: 46,
      backgroundColor: colors.input,
      color: colors.textPrimary,
      fontSize: 15,
      borderRadius: 10,
      paddingHorizontal: 12,
      marginBottom: 14,
    },
    inputFull: {
      paddingHorizontal: 16,
      marginBottom: 4,
    },
    listItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginHorizontal: 16,
      marginBottom: 8,
      borderRadius: 10,
    },
    iconBox: {
      width: 38,
      height: 38,
      borderRadius: 8,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    listItemText: {
      flexShrink: 1,
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '600',
    },
    listItemSub: {
      color: colors.textSecondary,
      fontSize: 13,
      marginTop: 4,
    },
    saveWrapper: {
      paddingHorizontal: 16,
      marginTop: 8,
      marginBottom: 16,
    },
    saveButton: {
      backgroundColor: colors.primary,
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
    },
    saveButtonText: {
      color: colors.onPrimary,
      fontWeight: '600',
      fontSize: 15,
    },
  });

  const novaReceitaStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      alignItems: 'stretch',
      paddingHorizontal: 10,
    },
    titulo: {
      flexShrink: 1,
      color: colors.textPrimary,
      marginLeft: 10,
      fontSize: 19,
      fontWeight: '600',
    },
    addValor: {
      flexWrap: 'wrap',
      gap: 12,
      flexDirection: 'row',
      backgroundColor: colors.surfaceMuted,
      padding: 12,
      margin: 16,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    InputValor: {
      color: colors.success,
      borderRadius: 10,
      flexGrow: 1,
      flexBasis: 140,
      minWidth: 0,
      backgroundColor: colors.input,
      minHeight: 46,
      paddingHorizontal: 10,
      justifyContent: 'center',
      fontWeight: '600',
      fontSize: 17,
    },
    input: {
      width: '100%',
      minHeight: 46,
      backgroundColor: colors.input,
      color: colors.textPrimary,
      fontSize: 15,
      borderRadius: 10,
      paddingHorizontal: 12,
      marginBottom: 14,
    },
    inputFull: {
      paddingHorizontal: 16,
      marginBottom: 4,
    },
    listItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginHorizontal: 16,
      marginBottom: 8,
      borderRadius: 10,
    },
    iconBox: {
      width: 38,
      height: 38,
      borderRadius: 8,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    listItemText: {
      flexShrink: 1,
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '600',
    },
    listItemSub: {
      color: colors.textSecondary,
      fontSize: 13,
      marginTop: 4,
    },
    saveWrapper: {
      paddingHorizontal: 16,
      marginTop: 8,
      marginBottom: 16,
    },
    saveButton: {
      backgroundColor: colors.primary,
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
    },
    saveButtonText: {
      color: colors.onPrimary,
      fontWeight: '600',
      fontSize: 15,
    },
  });

  const relatoriosStyles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      alignItems: 'stretch',
      paddingHorizontal: 10,
    },
    card: {
      backgroundColor: colors.surface,
      marginHorizontal: 18,
      marginBottom: 5,
      marginTop: 20,
      borderRadius: 22,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.border,
    },
    cardTitle: {
      color: colors.textPrimary,
      fontSize: 22,
      fontWeight: 'bold',
      marginBottom: 15,
    },
    pickerContainer: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    picker: {
      color: colors.textPrimary,
      height: 55,
    },
    itemResumo: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
      paddingBottom: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    textos: {
      marginLeft: 15,
      flex: 1,
    },
    label: {
      color: colors.textSecondary,
      fontSize: 15,
      marginBottom: 3,
    },
    valor: {
      color: colors.textPrimary,
      fontSize: 20,
      fontWeight: 'bold',
    },
    button: {
      backgroundColor: colors.primary,
      padding: 14,
      marginHorizontal: 18,
      marginTop: 10,
      height: 56,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
    },
    buttonText: {
      color: colors.onPrimary,
      fontSize: 17,
      fontWeight: 'bold',
      marginLeft: 10,
    },
  });
  return {
    dashboardStyles,
    fluxoFinanceiroStyles,
    inicioStyles,
    metasStyles,
    novaDespesaStyles,
    novaReceitaStyles,
    relatoriosStyles,
  };
}
