/** Estilos de barra inferior e menus de navegação, calculados com a paleta ativa. */
import { StyleSheet } from 'react-native';

export function createNavegacaoStyles(colors, { radii, shadow }) {
  const barraNavegacaoStyles = StyleSheet.create({
    fabPressable: {
      alignItems: 'center',
      justifyContent: 'center',
      flex: 1,
    },
    fab: {
      width: 70,
      height: 70,
      borderRadius: 35,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: -30,
      backgroundColor: colors.primary,
      borderWidth: 4,
      borderColor: colors.backgroundAlt,
      ...shadow.soft,
    },
    tabPressable: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 58,
    },
    tabAnimatedContent: {
      alignItems: 'center',
    },
    tabPill: {
      paddingHorizontal: 14,
      paddingVertical: 4,
      borderRadius: radii.pill,
    },
    tabText: {
      fontSize: 10,
      marginTop: 3,
      textAlign: 'center',
    },
    activeDot: {
      width: 4,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.primary,
      marginTop: 3,
    },
    expandedMenu: {
      position: 'absolute',
      bottom: 92,
      width: '94%',
      maxWidth: 420,
      alignSelf: 'center',
      paddingHorizontal: 8,
      backgroundColor: colors.surfaceAlt,
      borderRadius: radii.lg,
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-around',
      zIndex: 9,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadow.soft,
    },
    expandedMenuItem: {
      alignItems: 'center',
      justifyContent: 'center',
      width: '22%',
      paddingVertical: 10,
      marginVertical: 4,
      borderRadius: radii.md,
    },
    expandedMenuIcon: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.primarySoft,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 6,
    },
    expandedMenuLabel: {
      color: colors.textPrimary,
      fontSize: 11,
      fontWeight: '600',
      textAlign: 'center',
    },
    currentOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: colors.overlay,
      zIndex: 8,
    },
    currentTabBar: {
      position: 'absolute',
      bottom: 8,
      alignSelf: 'center',
      width: '94%',
      maxWidth: 420,
      zIndex: 10,
      flexDirection: 'row',
      minHeight: 76,
      paddingVertical: 6,
      borderRadius: radii.xl,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 6,
      alignItems: 'center',
      backgroundColor: colors.backgroundAlt,
      ...shadow.soft,
    },
  });
  return { barraNavegacaoStyles };
}
